### ISSUE TITLE
[BUG] Citizen search returns partial results

### ISSUE THREAD

**Issue by CaptNemoUK** [uee-life/uee.life.next#130]
When using the citizen search the results don't match all possibles.

For example, I type in Nemo and some results are returned but not myself. Then I type Capn and different results are returned but still not myself. When I type Capn_Nemo then my user shows up.

Some of the results when typing "Capn_" have a format similar to my username as in Capn_Naner for example and Capn_Dreadful but my user isn't provided in those results.

**Comment by CapnFlint** [comment]
Sadly this is a side effect of using the RSI citizen search functionality. I can look into including/prioritizing searching our back end database too potentially...
