### ISSUE TITLE
Unable to add new vehicle

### ISSUE THREAD

**Issue by CaptNemoUK** [uee-life/uee.life.next#275]
When attempting to add a new vehicle the following output is thrown up in the dev terminal

```
[Thu, 24 Oct 2024 23:28:55 GMT]-[NEO4J-Write]-[Anonymous] MATCH (c:Citizen)        WHERE c.id =~ $handle  ...
[Thu, 24 Oct 2024 23:28:55 GMT]-[API-CALL]-[Capn_Nemo] http://localhost:3000/api/admin/vehicles/add [POST]
[Thu, 24 Oct 2024 23:28:55 GMT]-[AUTH]-[Capn_Nemo] Requesting Permissions admin:all

 WARN  Access Denied from user undefined to resource undefined
```

The add OK button just throws this output and doesn't add the ship.

**Comment by CaptNemoUK** [comment]
Just tried again and this bug still exists in some form or other. Current attempts at adding a ship result in the following output:

api/admin/vehicles/add:1 
Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by CapnFlint** [comment]
Seems like your session is out of sync, tried logging out and back in?

**Comment by CapnFlint** [comment]
Working as intended. You weren't in the admins group :)
