### ISSUE TITLE
Assignment page output not shown

### ISSUE THREAD

**Issue by CaptNemoUK** [uee-life/uee.life.next#276]
When viewing assignments there appears to be a problem showing some information.

Clicking assignments then the fleet icon/button takes you to the following page:

https://uee.life/fleets/B9A4FB9D

This page shows this in the bottom left corner:

![Image](https://github.com/user-attachments/assets/8904b63b-89c0-4ef0-9241-b8895a4d0767)

**Comment by CapnFlint** [comment]
Didn't write this yet :D i should disable for now
