### ISSUE TITLE
POI's have an empty value in their Affiliation field

### ISSUE THREAD

**Issue by CapnFlint** [uee-life/uee.life.next#71]
The affiliation field for each POI should either reflect their affiliation, or "None" if no affiliation is present. Currently they are all empty.

**Comment by CapnFlint** [comment]
Could be a more challenging one for you @CaptNemoUK , we can work it together, as it may include needing to update the object data model, or doing specific checking of data within Nuxt.

**Comment by CapnFlint** [comment]
I'm actually not seeing this... Need to take a look through and call out specific examples please @CaptNemoUK

**Comment by CaptNemoUK** [comment]
Yeah, so I'm also no longer seeing this. in the returned objects. The POI logos don't appear in the default loaded Explore screen, they do now appear in the search results though. Was it this that you were noticing? I have a fix for this.

**Comment by CaptNemoUK** [comment]
Added the code for this as a second commit in my previous PR for the POI search bar. Can put it into a new branch if need be, I have one open ready.
