### ISSUE TITLE
Convert the "test site" banner into a generic notification banner

### ISSUE THREAD

**Issue by CapnFlint** [uee-life/uee.life.next#79]
We have a sexy new "test site" banner made by the one and only @CaptNemoUK . This has to also show on the mobile site, so we should convert it to a component to include in both layouts.

But, while we are at it, perhaps we should have a generic notification banner in case there are other important messages we need to send to all, or specific, people.

I propose we include a prop to specify type, and have the following types:
- Alert: Red background, high importance alert messages
- Warning: Yellow background, medium importance warning messages
- Note: Blue/green background? Low importance notification

It can be used for outages, bugs, account issues, etc.

**Comment by CaptNemoUK** [comment]
We may want to add more options to this component in the future but for an initial stab at it I think it meets our requirements.

**Comment by CaptNemoUK** [comment]
Marking as done. Further changes can be tracked in a new issue.
